'use strict';
// ============================================================
// HYBRID POST-QUANTUM KEM — the laptop-side port of elle-worker's
// src/pqc-hybrid.ts + src/pqc-qcmdpc.ts
// ============================================================
//
// Byte-for-byte port, same discipline as rosen-bridge.cjs: same algorithms,
// same constants, same domain-separation strings, same byte order. That is
// what lets a key encapsulated on one side decapsulate on the other.
//
//   K = HKDF-SHA256( ss_mlkem ‖ ss_x25519 [‖ ss_qcmdpc], info = transcript )
//
// An attacker must break EVERY leg to learn K, so the hybrid can never be
// weaker than its strongest leg. See elle-worker's docs/PQC_HYBRID.md for the
// full rationale; this header covers only what is port-specific.
//
// WHY THIS PORTS SAFELY:
//   • ML-KEM-768 and X25519 come from the SAME audited packages the worker
//     uses (@noble/post-quantum, @noble/curves), pinned to the same versions.
//     Pure JS, so they are bit-identical on workerd and on Node — that is
//     precisely why the worker chose them over a runtime-provided WebCrypto
//     curve.
//   • Node 19+ exposes globalThis.crypto with the same WebCrypto subtle the
//     Workers runtime implements, so HKDF and SHA-256 match.
//   • The QC-MDPC leg is our own code on both sides, so it is ported here
//     line-for-line rather than reimplemented.
//
// NOT ASSUMED — PROVEN: pqc-hybrid.test.cjs decapsulates test vectors
// GENERATED BY THE WORKER (fixtures/pqc-interop-vectors.json) and checks the
// shared secret matches byte-for-byte, and emits its own vectors for the
// worker's suite to verify in the other direction. The older rosen-bridge
// port's interop was only ever checked by hand; this one runs in CI.
//
// ⚠️ The QC-MDPC leg is HAND-ROLLED and UNREVIEWED — not constant-time,
// nonzero decoding-failure rate, modulo bias in the sampler, toy parameters.
// It is only ever ADDED to the vetted legs, never used alone: under the
// OR-security property a bug here costs availability, not confidentiality.
// ============================================================

const { ml_kem768 } = require('@noble/post-quantum/ml-kem.js');
const { x25519 } = require('@noble/curves/ed25519.js');
const { shake256 } = require('@noble/hashes/sha3.js');

// ── QC-MDPC parameters (must match src/pqc-qcmdpc.ts exactly) ───────────────
const QCMDPC_R = 4801;   // prime
const QCMDPC_DV = 45;    // odd weight per parity-check polynomial
const QCMDPC_T = 84;     // total error weight

const utf8 = (s) => new TextEncoder().encode(s);

function concatBytes(...parts) {
  let n = 0; for (const p of parts) n += p.length;
  const out = new Uint8Array(n); let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; }
  return out;
}

// ── polynomial helpers in R = F₂[x]/(xʳ − 1) ────────────────────────────────
function polySupport(a) {
  const idx = [];
  for (let i = 0; i < a.length; i++) if (a[i]) idx.push(i);
  return Int32Array.from(idx);
}

function polyMulSparse(dense, sparseSupport, r) {
  const out = new Uint8Array(r);
  for (let s = 0; s < sparseSupport.length; s++) {
    const k = sparseSupport[s];
    const split = r - k;
    for (let j = 0; j < split; j++) out[j + k] ^= dense[j];
    for (let j = split; j < r; j++) out[j + k - r] ^= dense[j];
  }
  return out;
}

function polyXor(a, b) {
  const out = new Uint8Array(a.length);
  for (let i = 0; i < a.length; i++) out[i] = a[i] ^ b[i];
  return out;
}

function polyIsZero(a) {
  for (let i = 0; i < a.length; i++) if (a[i]) return false;
  return true;
}

// ── inversion: binary extended Euclid on packed Uint32 bitsets ──────────────
function bsFrom(a, words) {
  const b = new Uint32Array(words);
  for (let i = 0; i < a.length; i++) if (a[i]) b[i >>> 5] |= 1 << (i & 31);
  return b;
}
function bsDeg(b) {
  for (let w = b.length - 1; w >= 0; w--) {
    if (b[w] !== 0) return (w << 5) + (31 - Math.clz32(b[w]));
  }
  return -1;
}
function bsXorShift(dst, src, shift) {
  const ws = shift >>> 5, bs = shift & 31;
  if (bs === 0) {
    for (let i = dst.length - 1; i >= ws; i--) dst[i] ^= src[i - ws];
  } else {
    for (let i = dst.length - 1; i >= ws; i--) {
      let v = src[i - ws] << bs;
      if (i - ws - 1 >= 0) v |= src[i - ws - 1] >>> (32 - bs);
      dst[i] ^= v;
    }
  }
}
function bsToPolyFold(b, r) {
  const out = new Uint8Array(r);
  const total = b.length << 5;
  for (let i = 0; i < total; i++) {
    if ((b[i >>> 5] >>> (i & 31)) & 1) out[i % r] ^= 1;
  }
  return out;
}

function polyInv(a, r) {
  const W = ((r + 64) >>> 5) + 1;
  let U = bsFrom(a, W);
  let V = new Uint32Array(W);
  V[0] |= 1; V[r >>> 5] |= 1 << (r & 31);
  let GU = new Uint32Array(W); GU[0] = 1;
  let GV = new Uint32Array(W);
  let dU = bsDeg(U), dV = bsDeg(V);
  if (dU < 0) return null;

  while (dU > 0) {
    if (dU < dV) {
      const tU = U; U = V; V = tU;
      const tG = GU; GU = GV; GV = tG;
      const td = dU; dU = dV; dV = td;
    }
    bsXorShift(U, V, dU - dV);
    bsXorShift(GU, GV, dU - dV);
    dU = bsDeg(U);
  }
  if (dU !== 0) return null;
  return bsToPolyFold(GU, r);
}

// ── sampling ────────────────────────────────────────────────────────────────
function randomBytes(n) {
  const b = new Uint8Array(n); crypto.getRandomValues(b); return b;
}

function sampleSparse(r, weight) {
  const out = new Uint8Array(r);
  let set = 0;
  while (set < weight) {
    const buf = new Uint32Array(64); crypto.getRandomValues(buf);
    for (let i = 0; i < buf.length && set < weight; i++) {
      const p = buf[i] % r;
      if (!out[p]) { out[p] = 1; set++; }
    }
  }
  return out;
}

// Deterministic — the FO re-derivation check depends on this matching the
// worker's implementation bit-for-bit (block size, counter encoding, and the
// little-endian 4-byte reads all matter).
function sampleError(seed, r, t) {
  const e0 = new Uint8Array(r), e1 = new Uint8Array(r);
  let set = 0, ctr = 0;
  while (set < t) {
    const ctrBytes = new Uint8Array(4);
    new DataView(ctrBytes.buffer).setUint32(0, ctr++, true);
    const blk = shake256(concatBytes(utf8('bike-err'), seed, ctrBytes), { dkLen: 1024 });
    const dv = new DataView(blk.buffer, blk.byteOffset, blk.byteLength);
    for (let i = 0; i + 4 <= blk.length && set < t; i += 4) {
      const v = dv.getUint32(i, true) % (2 * r);
      if (v < r) { if (!e0[v]) { e0[v] = 1; set++; } }
      else { const p = v - r; if (!e1[p]) { e1[p] = 1; set++; } }
    }
  }
  return { e0, e1 };
}

// ── byte helpers ────────────────────────────────────────────────────────────
function packPoly(a) {
  const out = new Uint8Array((a.length + 7) >> 3);
  for (let i = 0; i < a.length; i++) if (a[i]) out[i >> 3] |= 1 << (i & 7);
  return out;
}
function unpackPoly(bytes, r) {
  const out = new Uint8Array(r);
  for (let i = 0; i < r; i++) out[i] = (bytes[i >> 3] >> (i & 7)) & 1;
  return out;
}
function xorBytes(a, b) {
  const n = Math.min(a.length, b.length), out = new Uint8Array(n);
  for (let i = 0; i < n; i++) out[i] = a[i] ^ b[i];
  return out;
}
function polyEq(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

// ── the bit-flipping decoder ────────────────────────────────────────────────
function counters(syn, supp, r) {
  const c = new Int32Array(r);
  for (let s = 0; s < supp.length; s++) {
    const k = supp[s], split = r - k;
    for (let j = 0; j < split; j++) c[j] += syn[j + k];
    for (let j = split; j < r; j++) c[j] += syn[j + k - r];
  }
  return c;
}

function bfDecode(synIn, h0, h1, r, maxIter = 40) {
  const s0 = polySupport(h0), s1 = polySupport(h1);
  const syn = Uint8Array.from(synIn);
  const e0 = new Uint8Array(r), e1 = new Uint8Array(r);
  const floor = (QCMDPC_DV >> 1) + 1;

  const flip = (pos, supp) => {
    for (let s = 0; s < supp.length; s++) {
      let idx = pos + supp[s]; if (idx >= r) idx -= r;
      syn[idx] ^= 1;
    }
  };

  for (let iter = 0; iter < maxIter; iter++) {
    if (polyIsZero(syn)) return { e0, e1 };
    const c0 = counters(syn, s0, r), c1 = counters(syn, s1, r);
    let max = 0;
    for (let j = 0; j < r; j++) { if (c0[j] > max) max = c0[j]; if (c1[j] > max) max = c1[j]; }
    if (max === 0) return null;
    const thr = Math.max(max - 1, floor);
    let flipped = false;
    for (let j = 0; j < r; j++) {
      if (c0[j] >= thr) { e0[j] ^= 1; flip(j, s0); flipped = true; }
      if (c1[j] >= thr) { e1[j] ^= 1; flip(j, s1); flipped = true; }
    }
    if (!flipped) return null;
  }
  return polyIsZero(syn) ? { e0, e1 } : null;
}

// ── the QC-MDPC KEM ─────────────────────────────────────────────────────────
function qcmdpcKeygen(r = QCMDPC_R, dv = QCMDPC_DV) {
  for (let attempt = 0; attempt < 64; attempt++) {
    const h0 = sampleSparse(r, dv);
    const inv = polyInv(h0, r);
    if (!inv) continue;
    const h1 = sampleSparse(r, dv);
    const h = polyMulSparse(inv, polySupport(h1), r);
    return { publicKey: { h, r }, secretKey: { h0, h1, r, sigma: randomBytes(32) } };
  }
  throw new Error('qcmdpc: keygen failed to find an invertible h0');
}

const L = (e0, e1) =>
  shake256(concatBytes(utf8('bike-L'), packPoly(e0), packPoly(e1)), { dkLen: 32 });
const KDF = (m, ct) =>
  shake256(concatBytes(utf8('bike-K'), m, packPoly(ct.c0), ct.c1), { dkLen: 32 });

function qcmdpcEncaps(pk) {
  const r = pk.r;
  const m = randomBytes(32);
  const { e0, e1 } = sampleError(m, r, QCMDPC_T);
  const c0 = polyXor(e0, polyMulSparse(pk.h, polySupport(e1), r));
  const c1 = xorBytes(m, L(e0, e1));
  const ct = { c0, c1 };
  return { ciphertext: ct, sharedSecret: KDF(m, ct) };
}

function qcmdpcDecaps(sk, ct) {
  const r = sk.r;
  const syn = polyMulSparse(ct.c0, polySupport(sk.h0), r);
  const dec = bfDecode(syn, sk.h0, sk.h1, r);
  if (dec) {
    const m2 = xorBytes(ct.c1, L(dec.e0, dec.e1));
    const re = sampleError(m2, r, QCMDPC_T);
    if (polyEq(re.e0, dec.e0) && polyEq(re.e1, dec.e1)) return KDF(m2, ct);
  }
  return shake256(concatBytes(utf8('bike-reject'), sk.sigma, packPoly(ct.c0), ct.c1), { dkLen: 32 });
}

// ── the hybrid combiner ─────────────────────────────────────────────────────
async function transcript(pk, ct) {
  const parts = [utf8(`elle-pqc-hybrid-v1|${ct.profile}|`), pk.mlkem, pk.x25519, ct.mlkem, ct.epk];
  if (ct.qcmdpc && pk.qcmdpc) parts.push(packPoly(pk.qcmdpc.h), packPoly(ct.qcmdpc.c0), ct.qcmdpc.c1);
  const digest = await crypto.subtle.digest('SHA-256', concatBytes(...parts));
  return new Uint8Array(digest);
}

async function combine(secrets, info) {
  const ikm = concatBytes(...secrets);
  const base = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'HKDF', hash: 'SHA-256', salt: new Uint8Array(0), info }, base, 256,
  );
  return new Uint8Array(bits);
}

function pqcHybridKeygen(profile = 'vetted') {
  const kem = ml_kem768.keygen();
  const xsk = x25519.utils.randomSecretKey();
  const xpk = x25519.getPublicKey(xsk);
  const pk = { profile, mlkem: kem.publicKey, x25519: xpk };
  const sk = { profile, mlkem: kem.secretKey, x25519: xsk };
  if (profile === 'experimental') {
    const q = qcmdpcKeygen();
    pk.qcmdpc = q.publicKey;
    sk.qcmdpc = q.secretKey;
  }
  return { publicKey: pk, secretKey: sk };
}

async function pqcHybridEncaps(pk) {
  const kem = ml_kem768.encapsulate(pk.mlkem);
  const esk = x25519.utils.randomSecretKey();
  const epk = x25519.getPublicKey(esk);
  const ssX = x25519.getSharedSecret(esk, pk.x25519);

  const ct = { profile: pk.profile, mlkem: kem.cipherText, epk };
  const legs = [kem.sharedSecret, ssX];

  if (pk.profile === 'experimental') {
    if (!pk.qcmdpc) throw new Error('pqc-hybrid: experimental profile requires a qcmdpc public key');
    const q = qcmdpcEncaps(pk.qcmdpc);
    ct.qcmdpc = q.ciphertext;
    legs.push(q.sharedSecret);
  }

  return { ciphertext: ct, sharedSecret: await combine(legs, await transcript(pk, ct)) };
}

async function pqcHybridDecaps(sk, pk, ct) {
  if (ct.profile !== sk.profile) throw new Error('pqc-hybrid: profile mismatch');
  const ssKem = ml_kem768.decapsulate(ct.mlkem, sk.mlkem);
  const ssX = x25519.getSharedSecret(sk.x25519, ct.epk);
  const legs = [ssKem, ssX];

  if (sk.profile === 'experimental') {
    if (!sk.qcmdpc || !ct.qcmdpc) throw new Error('pqc-hybrid: experimental profile requires the qcmdpc leg');
    legs.push(qcmdpcDecaps(sk.qcmdpc, ct.qcmdpc));
  }

  return combine(legs, await transcript(pk, ct));
}

// ── interop vector (de)serialization ────────────────────────────────────────
// The wire form both repos' test suites read and write. Hex keeps it diffable
// and avoids any base64 padding ambiguity between runtimes.
const toHex = (u8) => Buffer.from(u8).toString('hex');
const fromHex = (s) => new Uint8Array(Buffer.from(s, 'hex'));

function exportVector(pk, sk, ct, sharedSecret) {
  const v = {
    profile: pk.profile,
    publicKey: { mlkem: toHex(pk.mlkem), x25519: toHex(pk.x25519) },
    secretKey: { mlkem: toHex(sk.mlkem), x25519: toHex(sk.x25519) },
    ciphertext: { mlkem: toHex(ct.mlkem), epk: toHex(ct.epk) },
    shared_secret: toHex(sharedSecret),
  };
  if (pk.profile === 'experimental') {
    v.publicKey.qcmdpc = { h: toHex(packPoly(pk.qcmdpc.h)), r: pk.qcmdpc.r };
    v.secretKey.qcmdpc = {
      h0: toHex(packPoly(sk.qcmdpc.h0)), h1: toHex(packPoly(sk.qcmdpc.h1)),
      r: sk.qcmdpc.r, sigma: toHex(sk.qcmdpc.sigma),
    };
    v.ciphertext.qcmdpc = { c0: toHex(packPoly(ct.qcmdpc.c0)), c1: toHex(ct.qcmdpc.c1) };
  }
  return v;
}

function importVector(v) {
  const pk = { profile: v.profile, mlkem: fromHex(v.publicKey.mlkem), x25519: fromHex(v.publicKey.x25519) };
  const sk = { profile: v.profile, mlkem: fromHex(v.secretKey.mlkem), x25519: fromHex(v.secretKey.x25519) };
  const ct = { profile: v.profile, mlkem: fromHex(v.ciphertext.mlkem), epk: fromHex(v.ciphertext.epk) };
  if (v.profile === 'experimental') {
    const r = v.publicKey.qcmdpc.r;
    pk.qcmdpc = { h: unpackPoly(fromHex(v.publicKey.qcmdpc.h), r), r };
    sk.qcmdpc = {
      h0: unpackPoly(fromHex(v.secretKey.qcmdpc.h0), r),
      h1: unpackPoly(fromHex(v.secretKey.qcmdpc.h1), r),
      r, sigma: fromHex(v.secretKey.qcmdpc.sigma),
    };
    ct.qcmdpc = { c0: unpackPoly(fromHex(v.ciphertext.qcmdpc.c0), r), c1: fromHex(v.ciphertext.qcmdpc.c1) };
  }
  return { pk, sk, ct, sharedSecret: fromHex(v.shared_secret) };
}

module.exports = {
  QCMDPC_R, QCMDPC_DV, QCMDPC_T,
  polySupport, polyMulSparse, polyInv, packPoly, unpackPoly, sampleSparse, sampleError,
  qcmdpcKeygen, qcmdpcEncaps, qcmdpcDecaps, bfDecode,
  pqcHybridKeygen, pqcHybridEncaps, pqcHybridDecaps,
  exportVector, importVector, toHex, fromHex,
};
